# make -o to dump the VAL

.PHONY: clean hello

OBJ = add.o div.o sub.o mul.o main.o
TARGET = main

$(TARGET).elf : $(OBJ)
	$(CC) $(OBJ) -o $@

main.o : main.c
	$(CC) -c $^ -o $@

add.o : add.c
	$(CC) -c $^ -o $@

div.o : div.c
	$(CC) -c $^ -o $@

sub.o : sub.c
	$(CC) -c $^ -o $@

mul.o : mul.c
	$(CC) -c $^ -o $@

hello :
	@echo "hello test"

clean :
	@$(RM) $(OBJ) $(TARGET).elf
	@echo "make clean finish"