[package]
name = "n03_call_mbedtls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mbedtls-sys-auto = "2.28.0"
openssl-sys = "0.9.88"